project:
  type: website

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: Contenido
        href: index.qmd
      - section: "Plano"
        contents:
          - href: sections/section0.qmd
            text: Acerca de
          - href: sections/section1.qmd
            text: Sección 1
          - href: sections/section2.qmd
            text: Rectas
          - href: sections/section3.qmd
            text: Independencia lineal
      - section:  Matrices 2 x  2
        contents:
          - href: sections/section4.qmd
            text: Matrices
          - href: sections/section5.qmd
            text: Solución de sistema de ecuaciones
          - href: sections/section6.qmd
            text: Trabajo computacional
          - href: sections/section9.qmd
            text: Autovalores y autovectores
      - section: Matrices N x N
        contents:
          - href: sections/section10.qmd
            text: Matrices
          - href: sections/section11.qmd
            text: Determinantes
          - href: sections/section11.qmd
            text: Determinantes 2
      - section: Transformaciones
        contents:
          - href: sections/section12.qmd
            text: Vectores en R
      - section: "Talleres"
        contents:
          - href: talleres/taller1.qmd
            text: Taller 1
          - href: talleres/taller2.qmd
            text: Taller 2
          - href: talleres/taller3.qmd
            text: Taller 3 (matrices)
          - href: talleres/taller4.qmd
            text: Taller 4 (Valores propios)
          - href: talleres/taller5.qmd
            text: Taller 5 (Valores propios)
          - href: talleres/taller6.qmd
            text: Taller resumen 
          - href: talleres/taller7.qmd
            text: Taller Operaciones con matrices n x n
          - href: talleres/taller8.qmd
            text: Vectores y matrices 
          - href: talleres/taller9.qmd
            text: Vectores y matrices II
          - href: talleres/taller10.qmd
            text: Subespacios vectoriales
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



